import { useEffect, useState } from "react";
import { BarChart3, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { RichContent } from "@/components/rich-content";
import type { QuestionAsset } from "@/domain/exam";

type QuestionRow = { id: string; prompt: string; type: string; points: number; assets: QuestionAsset[]; assigned: number; answered: number; omissions: number; correct: number; incorrect: number | null; accuracy: number | null; incorrectPercentage: number | null; averagePoints: number | null; averageDurationMs: number | null; section: string | null; difficulty: string | null; distribution: Array<{ answer: string; count: number }> };
type Analytics = { summary: Record<string, number | null>; gradeDistribution: Array<{ from: number; to: number; count: number }>; questions: QuestionRow[]; hardest: QuestionRow[]; easiest: QuestionRow[]; sections: Array<{ name: string; assigned: number; accuracy: number | null }>; difficulty: Array<{ name: string; assigned: number; accuracy: number | null }>; usesDifficulty: boolean; integrity: { totalSignals: number; affectedParticipants: number; byType: Array<{ type: string; count: number; participants: number }>; caveat: string } };
export interface AnalyticsEnvelope { current: { run: { id: string; title: string; code: string; createdAt: number }; analytics: Analytics }; aggregate: Analytics; perRun: Array<{ run: { id: string; title: string; code: string; createdAt: number }; analytics: Analytics }> }

export function AnalyticsPanel({ data }: { data: AnalyticsEnvelope }) {
  const [scope, setScope] = useState<"run" | "aggregate">("run");
  const [selectedRunId, setSelectedRunId] = useState(data.current.run.id);
  const [selectedQuestionId, setSelectedQuestionId] = useState<string | null>(null);
  const [ready, setReady] = useState(false);
  useEffect(() => { setReady(true); }, []);
  const selectedRun = data.perRun.find((item) => item.run.id === selectedRunId) ?? data.current;
  const analytics = scope === "run" ? selectedRun.analytics : data.aggregate;
  const summary = analytics.summary;
  const selectedQuestion = analytics.questions.find((question) => question.id === selectedQuestionId) ?? null;
  const maxBucket = Math.max(1, ...analytics.gradeDistribution.map((bucket) => bucket.count));
  return <section className={`grid gap-5 rounded-lg border bg-paper p-5 shadow-card transition duration-300 motion-reduce:transition-none ${ready ? "translate-y-0 opacity-100" : "translate-y-1 opacity-0"}`} aria-labelledby="analytics-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.08em] text-muted">Histórico de la evaluación</p><h2 id="analytics-title" className="mt-1 flex items-center gap-2 text-xl font-semibold text-ink"><BarChart3 className="size-5 text-brand" />Analítica</h2></div><div className="flex flex-wrap gap-1">{scope === "run" && data.perRun.length > 1 ? <label className="sr-only" htmlFor="analytics-run">Toma</label> : null}{scope === "run" && data.perRun.length > 1 ? <select id="analytics-run" value={selectedRunId} onChange={(event) => { setSelectedRunId(event.target.value); setSelectedQuestionId(null); }} className="h-9 rounded-md border bg-white px-2 text-sm text-ink">{[...data.perRun].reverse().map((item) => <option key={item.run.id} value={item.run.id}>{item.run.code} · {new Date(item.run.createdAt).toLocaleDateString("es-AR")}</option>)}</select> : null}<Button type="button" size="sm" variant={scope === "run" ? "default" : "outline"} onClick={() => { setScope("run"); setSelectedQuestionId(null); }}>Una toma</Button><Button type="button" size="sm" variant={scope === "aggregate" ? "default" : "outline"} onClick={() => { setScope("aggregate"); setSelectedQuestionId(null); }}>Todas ({data.perRun.length})</Button></div></div>
    <div className="grid gap-2 sm:grid-cols-3 xl:grid-cols-6">{[["Alumnos", summary.participants], ["Entregas", summary.submissions], ["Ausentes", summary.absences], ["Promedio", percent(summary.average)], ["Mediana", percent(summary.median)], ["Mín / Máx", `${percent(summary.min)} / ${percent(summary.max)}`], ["Aprobación", summary.passPercentage === null ? "Sin umbral" : percent(summary.passPercentage)], ["Duración media", duration(summary.averageDurationMs)], ["Duración mediana", duration(summary.medianDurationMs)], ["Duración mín / máx", `${duration(summary.minDurationMs)} / ${duration(summary.maxDurationMs)}`]].map(([label, value], index) => <div key={String(label)} className={`rounded-md bg-inset p-3 transition duration-300 motion-reduce:transition-none ${ready ? "translate-y-0 opacity-100" : "translate-y-1 opacity-0"}`} style={{ transitionDelay: ready ? `${Math.min(index * 35, 245)}ms` : "0ms" }}><p className="text-xs text-muted">{label}</p><p className="mono-number mt-1 text-lg font-semibold text-ink">{value ?? "—"}</p></div>)}</div>
    <div><h3 className="text-sm font-semibold text-ink">Distribución de notas</h3><div className="mt-3 flex h-36 items-end gap-1 border-b">{analytics.gradeDistribution.map((bucket, index) => <div key={bucket.from} className="group flex h-full flex-1 flex-col justify-end"><span className="mb-1 text-center text-[10px] text-muted">{bucket.count}</span><div className="min-h-0 bg-brand transition-[height] duration-500 motion-reduce:transition-none" style={{ height: ready ? `${bucket.count / maxBucket * 100}%` : "0%", transitionDelay: ready ? `${index * 35}ms` : "0ms" }} /><span className="mt-1 text-center text-[9px] text-muted">{bucket.from}</span></div>)}</div></div>
    <div className="grid gap-4 lg:grid-cols-2"><Rank title="Más difíciles" rows={analytics.hardest} onOpen={setSelectedQuestionId} /><Rank title="Más fáciles" rows={analytics.easiest} onOpen={setSelectedQuestionId} /></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-inset text-xs text-ink-2"><tr><th className="px-3 py-2">Pregunta</th><th className="px-3 py-2 text-right">Asignada</th><th className="px-3 py-2 text-right">Acierto</th><th className="px-3 py-2 text-right">Omisiones</th><th className="px-3 py-2">Distribución</th></tr></thead><tbody className="divide-y">{analytics.questions.map((question) => <tr key={question.id}><th className="max-w-72 px-3 py-3 font-medium text-ink"><button type="button" className="text-left hover:text-brand hover:underline" onClick={() => setSelectedQuestionId(question.id)}>{question.prompt}</button></th><td className="mono-number px-3 text-right">{question.assigned}</td><td className="mono-number px-3 text-right">{question.accuracy === null ? "manual" : percent(question.accuracy)}</td><td className="mono-number px-3 text-right">{question.omissions}</td><td className="px-3 text-xs text-muted">{question.distribution.slice(0, 4).map((item) => `${item.answer}: ${item.count}`).join(" · ") || "—"}</td></tr>)}</tbody></table></div>
    {selectedQuestion ? <QuestionDetail question={selectedQuestion} onClose={() => setSelectedQuestionId(null)} /> : null}
    <div className="grid gap-4 lg:grid-cols-3"><Groups title="Por sección" rows={analytics.sections} />{analytics.usesDifficulty ? <Groups title="Por dificultad" rows={analytics.difficulty} /> : null}<aside className="rounded-md border border-warn/25 p-4"><h3 className="flex items-center gap-2 text-sm font-semibold text-ink"><ShieldAlert className="size-4 text-warn" />Integridad</h3><p className="mono-number mt-3 text-xl font-semibold">{analytics.integrity.totalSignals} señales</p><p className="mt-1 text-xs text-muted">{analytics.integrity.affectedParticipants} alumnos con alguna señal.</p>{analytics.integrity.byType.length ? <ul className="mt-3 grid gap-1 text-xs text-ink-2">{analytics.integrity.byType.map((item) => <li key={item.type}>{signalLabel(item.type)} · {item.participants} alumno{item.participants === 1 ? "" : "s"} ({item.count} señal{item.count === 1 ? "" : "es"})</li>)}</ul> : null}<p className="mt-3 text-xs leading-5 text-muted">{analytics.integrity.caveat}</p></aside></div>
  </section>;
}

function Rank({ title, rows, onOpen }: { title: string; rows: QuestionRow[]; onOpen: (id: string) => void }) { return <section className="rounded-md border p-4"><h3 className="text-sm font-semibold text-ink">{title}</h3><ol className="mt-3 grid gap-2">{rows.map((row) => <li key={row.id}><button type="button" className="flex w-full justify-between gap-3 text-left text-sm hover:text-brand" onClick={() => onOpen(row.id)}><span className="truncate text-ink-2">{row.prompt}</span><span className="mono-number shrink-0 font-semibold">{percent(row.accuracy)}</span></button></li>)}{!rows.length ? <li className="text-sm text-muted">Sin datos automáticos.</li> : null}</ol></section>; }
function Groups({ title, rows }: { title: string; rows: Array<{ name: string; assigned: number; accuracy: number | null }> }) { return <section className="rounded-md border p-4"><h3 className="text-sm font-semibold text-ink">{title}</h3><dl className="mt-3 grid gap-2">{rows.map((row) => <div key={row.name} className="flex justify-between gap-3 text-sm"><dt>{row.name}</dt><dd className="mono-number">{percent(row.accuracy)} · n={row.assigned}</dd></div>)}</dl></section>; }
function QuestionDetail({ question, onClose }: { question: QuestionRow; onClose: () => void }) { return <article className="rounded-md border border-brand/25 bg-inset p-4" aria-labelledby={`analytics-detail-${question.id}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.08em] text-brand">Detalle por pregunta</p><RichContent id={`analytics-detail-${question.id}`} text={question.prompt} assets={question.assets} className="mt-2 font-semibold text-ink" /></div><Button type="button" size="sm" variant="ghost" onClick={onClose}>Cerrar</Button></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4">{[["Tipo", typeLabel(question.type)], ["Sección", question.section ?? "Sin sección"], ["Dificultad", difficultyLabel(question.difficulty)], ["Puntaje", `${question.points} pts`], ["Correctas", question.accuracy === null ? "Corrección manual" : `${question.correct} · ${percent(question.accuracy)}`], ["Incorrectas", question.incorrect === null ? "No aplica" : `${question.incorrect} · ${percent(question.incorrectPercentage)}`], ["Omitidas", String(question.omissions)], ["Puntaje promedio", question.averagePoints === null ? "Sin corregir" : `${question.averagePoints} / ${question.points}`], ["Tiempo promedio", question.averageDurationMs === null ? "Sin medición fiable" : duration(question.averageDurationMs)]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 font-semibold text-ink-2">{value}</dd></div>)}</dl><div className="mt-4"><p className="text-xs font-semibold text-ink-2">{question.type === "long" ? "Distribución de puntajes" : "Distribución de respuestas"}</p><div className="mt-2 flex flex-wrap gap-2">{question.distribution.map((item) => <span key={item.answer} className="rounded-full border bg-white px-2.5 py-1 text-xs text-ink-2">{item.answer} · {item.count}</span>)}{!question.distribution.length ? <span className="text-xs text-muted">Sin datos.</span> : null}</div></div></article>; }
function percent(value: unknown) { return typeof value === "number" ? `${value.toLocaleString("es-AR", { maximumFractionDigits: 1 })}%` : "—"; }
function duration(value: unknown) { if (typeof value !== "number") return "—"; const minutes = Math.floor(value / 60000); const seconds = Math.round((value % 60000) / 1000); return `${minutes}m ${seconds}s`; }
function typeLabel(value: string) { return ({ mc: "Opción múltiple", ms: "Respuesta múltiple", tf: "Verdadero / falso", sa: "Respuesta corta", long: "Desarrollo" } as Record<string, string>)[value] ?? value; }
function difficultyLabel(value: string | null) { return value ? ({ easy: "Fácil", medium: "Media", hard: "Difícil" } as Record<string, string>)[value] ?? value : "Sin definir"; }
function signalLabel(value: string) { return value.replaceAll("-", " "); }
